### ISSUE TITLE
Popover is bouncing when it shows up.

### ISSUE THREAD

**Issue by kolyneh** [doomsower/react-native-modal-popover#1]
Popover is bouncing when it shows up, but the arrow.

**Comment by doomsower** [comment]
Sorry, I don't get what you mean. I updated android styles a little, added example and animated gifs. They look alright to me, is your problem visible on those gifs?

**Comment by RP20** [comment]
same issue
@kolyneh did you resolved that bouncing popover ? it's only for android

**Comment by doomsower** [comment]
Can you provide some code example, so I can see this bouncing? Because I don't see anything wrong with popovers in my app, and the gif looks alright to me too.

**Comment by drakmail** [comment]
I'm doesn't have any issues with my android setup, @kolyneh @RP20 could you provide snippet of the code leading to issue?

**Comment by lytrunghieu** [comment]
same issuse

**Comment by doomsower** [comment]
I'm closing this in favor of #2
