### ISSUE TITLE
Allow custom duration, animation and easing

### ISSUE THREAD

**Issue by Frexuz** [doomsower/react-native-modal-popover#14]
Please add this :)

I think 300 is slow ;) I always use 200. And the scale animation, and the bounce easing is not our app's style.

**Comment by doomsower** [comment]
Implemented this since v0.0.5

**Comment by Frexuz** [comment]
Seems great :P But from my understanding, the tooltip still scales up/down, right?
Would it be possible to override that as well? Let's say with a fade-in/out

**Comment by doomsower** [comment]
Yes, you can only control duration and easing. Adding ability to customize animation in general will be complicated, and I want to keep this lib simple. You should fork and modify sources if you wish fading animation.

**Comment by Frexuz** [comment]
Ok thank for the answer :)
