### ISSUE TITLE
Popover anchor not being anchored with orientation change

### ISSUE THREAD

**Issue by mattmarkham** [doomsower/react-native-modal-popover#16]
Hello, when I switch orientation the popover seems to be anchored to the coordinates initially rendered on the app startup. If I start in portrait mode it will be anchored correctly then switching to landscape will place the popover with the same coordinates as portrait mode (leaving it in an awkward place on the screen). This occurs for me on android and iOS.

![popovermodallandscape](https://user-images.githubusercontent.com/26859639/36445842-4fe8b27c-1634-11e8-9443-a1ba3af37bae.png)
![popovermodalportrait](https://user-images.githubusercontent.com/26859639/36445844-501b97aa-1634-11e8-833d-8b42e7238dbe.png)

The only change I made to Popover.js was to add the supported orientations otherwise the whole screens orientation would not rotate. <react_native_1.Modal transparent visible={this.state.visible} onRequestClose={this.props.onClose} supportedOrientations={['portrait', 'landscape']}>
![popovermodalsidewaysportrait](https://user-images.githubusercontent.com/26859639/36446470-32a2be04-1636-11e8-9d19-367fb395c347.png)

setButton = (e) => {
      const handle = findNodeHandle(this.button);
      if (handle) {
        NativeModules.UIManager.measure(handle, (x0, y0, width, height, x, y) => {
          this.setState({ popoverAnchor: { x, y, width, height } });
        });
        console.log(this.state.popoverAnchor);
      }
    };
...
render() {
  return (
   <View style={popoverContainer}>
     <PopoverTouchable onPopoverDisplayed={() => console.log(this.state.popoverAnchor)}>
                     <Button
                       buttonRef={ (c) => (this.button = c) }
                       style={{ alignSelf: 'center' }}
                       onPress={() => this.setState({ showPopover: true })}
                       onLayout={this.setButton.bind(this)}
                     >
                        Filters
                     </Button>
                     <Popover
                       visible={this.state.showPopover}
                       fromRect={this.state.popoverAnchor}
                       contentStyle={styles.content}
                       arrowStyle={styles.arrow}
                       backgroundStyle={styles.background}
                       onClose={() => this.setState({ showPopover: false })}
                       placement='bottom'
                     >
...
                    </Popover>
       </PopoverTouchable>
    </View>

**Comment by doomsower** [comment]
Seems that code that should handles screen orientation change should be added to popover. I'll try to find some time and look into this. Or you could try yourself and submit PR

**Comment by mattmarkham** [comment]
So after some additional tinkering today, I fixed my issue by adding the displayArea prop to the popover component, and setting those values based on orientation in my render method.

Correct me if I am wrong but I think displayArea is a required prop to deal with orientation change, otherwise it will use the value calculated during initial render in Popover.js.

**Comment by doomsower** [comment]
You're right. Popover is will be recomputed when `fromRect` or `displayArea` changes. This is about default `displayArea`. If it is undefined, then default value is used, and this default value is set only once, and doesn't account for orientation changes. This should be changed inside the module. But if user sets `displayArea` manually, it's his responsibility to track `displayArea` changes

**Comment by doomsower** [comment]
Ok, this is implemented in version 0.0.6
