### ISSUE TITLE
No declaration of module 'react-native-modal-popover' error, when trying to use the dependency on a .tsx file

### ISSUE THREAD

**Issue by jerryheir** [doomsower/react-native-modal-popover#24]
No declaration of module 'react-native-modal-popover' error, when trying to use the dependency on a .tsx file

I created a .tsx file and checked for index.d.ts in the node modules, I saw it . I then when ahead to import Popover , PopoverController from 'react-native-modal-popover' but it gives me the error **Cannot find module 'react-native-modal-popover'** 
Could not find a declaration file for module 'react-native-modal-popover'. 'c:/Users/react-native-typescript/node_modules/react-native-modal-popover/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-native-modal-popover` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-modal-popover';`

**Comment by doomsower** [comment]
Which version are you using?
`types` were missing from `package.json` until few days ago.

**Comment by jerryheir** [comment]
I added types to the package.json and it worked fine.. I think I'll need to
update to the latest version also. Thanks a lot
