### ISSUE TITLE
Allow usage of other animation libraries

### ISSUE THREAD

**Issue by AdamGerthel** [doomsower/react-native-modal-popover#25]
At the moment, the module uses its own animation for the popover, making it impossible to use another library like [React Move](https://github.com/react-tools/react-move) or [React Motion](https://github.com/chenglou/react-motion). Is it possible to refactor to allow custom animations, or at least to disable the built in animation so that other libraries could be used?

**Comment by doomsower** [comment]
I’m not familiar with any of these libraries, and certainly won’t have time to investigate this feature in near future. But I will gladly accept PR

Konstantin Kuznetsov

**Comment by AdamGerthel** [comment]
Thanks for the quick reply - I found your reply from https://github.com/doomsower/react-native-modal-popover/issues/14 after writing this issue, and I think using a custom easing function along with duration might be good enough for me. Closing!
