### ISSUE TITLE
How to show in center of screen

### ISSUE THREAD

**Issue by ansarikhurshid786** [doomsower/react-native-modal-popover#37]
it is working perfectly. i am facing issue to get value of x,y,widh and height. 

can someone help me to show middle of screen ?

**Comment by doomsower** [comment]
This module is about popovers which are anchored to other views. If you need to display it in the middle of the screen, simple modal or react-native-modal should suffice.

**Comment by ansarikhurshid786** [comment]
how to get x,y,height and widht value ?

**Comment by doomsower** [comment]
Of what? Anchor element or popover content? Use `onLayout` or  `measure`. Or is that module internals prevent you from tapping into these methods?

**Comment by ansarikhurshid786** [comment]
can you please give me sample code of onLayout or measure? I tried measure but measure is not a function.

**Comment by doomsower** [comment]
Just search the source code of this project. I use both `onLayout` and `measure` here.

**Comment by ansarikhurshid786** [comment]
ok thanks for your reply. i am using modal. i tried a lot but not working(onlayout, measure, measurelayout)
