### ISSUE TITLE
Modal not displaying after navigating from react-native-modal-popover 

### ISSUE THREAD

**Issue by kishanbharda** [doomsower/react-native-modal-popover#38]
I have a screen in which I have added a component called `<Loader />`. This `<Loader />` component renders the a modal, which contains the `ActivityIndicator`.  Basically `<Loader />` component renders the `ActivityIndicator` in react-native `modal` to displays the loading in full screen. Now, If I come in screen where `<Loader />` component is added from StackNavigator or elsewhere then it displays the loading ActivityIndicator.

But the problem is that, if I navigate to screen where this `<Loader />` component is added, from `react-native-modal-popover` then `<Loader />` component does not displaying the ActivityIndicator. Actually Modal is not displaying.

Here is the problem explanation gif :

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/39869106/63686369-565d3080-c81f-11e9-9dbf-4306a321f72d.gif)

As you can see, If I navigate to screen from some of list item then modal is displayed with ActivityIndicator but if I navigate from react-native-modal-popover then modal is not displaying.

How to solve it ?

**Comment by doomsower** [comment]
react-native doesn't allow us to have two visible modals at the same time. You have to close popover before showing the other modal with loading indicator. Moreover, you should make sure that modal disappearance animation has completed before you show another modal. Not sure if I provide proper event handler for this though. Are sure you need modal for loading indicator and the simple overlay won't do it?

**Comment by kishanbharda** [comment]
Thanks @doomsower !!!

Now, I found that whenever I navigate to another page, at that time popover actually not completing its animation even if I called `closePopover()` method. So I added `setTimeout()` before navigating to another page. 

Here is the code that solved my issue : 

```lang-js
handleOnPressPopover = (key, closePopover) => {
	closePopover();
	setTimeout(() => {
		switch (key) {
			case PopoverKeys.DELETEORDER: {
				this.deleteOrder();
				break;
			}
			case PopoverKeys.EDITORDER: {
				this.props.navigation.navigate("EditOrder");
				break;
			}
			case PopoverKeys.VIEWORDER: {
				this.props.navigation.navigate("ViewOrder");
				break;
			}
			default: {
				this.props.navigation.navigate("ViewOrder");
				break;
			}
		}
	}, 100); // time is same as popover's props 'duration' value
}
```

**Note** : Set timeout time same as value of popover's props '**_duration_**'.
