### ISSUE TITLE
Visible prop is not working.

### ISSUE THREAD

**Issue by rhenmark** [doomsower/react-native-modal-popover#4]
Hi sir visible prop is not working. Any example sir for visible prop? I cannot get working on my side. Here is my code: 

> 

> `<PopoverTouchable onPopoverDisplayed={() => console.log('show')}>
	<TouchableOpacity style={styles.profileAction_btn}>
		<MyIcon name='report' color='#fff' size={22}/>
	</TouchableOpacity>
      	<Popover
      		placement='left'
        	contentStyle={styles.content}
        	arrowStyle={styles.arrow}
        	backgroundStyle={styles.background}
        	visible={this.state.visible}
      	>
	      	<TouchableOpacity style={styles.reportBtn}>
		        <Text style={[styles.txtWhite, styles.font_medium]}>Block User</Text>
	      	</TouchableOpacity>
	      	<TouchableOpacity style={styles.reportBtn} onPress={() => {
	      			this.setState({
	      				visible: false
	      			})
	      		}}>
		        <Text style={[styles.txtWhite, styles.font_medium]}>Report User</Text>
	      	</TouchableOpacity>
      </Popover>
</PopoverTouchable>`

**Comment by doomsower** [comment]
If you use `PopoverTouchable` touchable you don't need to control `visible` prop of `Popover`.
It is design for simple use with info popovers. If you need more complicated controlled behavior, you should use `Popover` alone, and in this case you are in control of its `visible` prop.
You can check out `PopoverTouchable` source code and see what it does.

**Comment by rhenmark** [comment]
Okay. Now it is clear to me. Tnx again 💯
