### ISSUE TITLE
How to set align for content of Popoper

### ISSUE THREAD

**Issue by lytrunghieu** [doomsower/react-native-modal-popover#5]
I'm using prop visible to controll open/hide of popoper but I can't align for content to center , My code:
render() {
    return (
      <Popover
        visible={this.state.visible}
        contentStyle={styles.tooltipContent}
        arrowStyle={styles.tooltipArrow}
        backgroundStyle={styles.tooltipBg}
        placement = {"bottom"}
        fromRect={{x: this.state.x, y: this.state.y, width: this.state.width, height: this.state.height}}
      >
        <Text text="hello"/>
      </Popover>
    )
  }
tooltipBg :{
    backgroundColor:"rgba(0,0,0,0.3)",
    alignItems:"center",
  },

  tooltipArrow :{
    backgroundColor:"rgba(0,0,0,0)"
  },

  tooltipContent :{
    width : "90%",
    backgroundColor: 'white',
    borderRadius: 8,
    alignSelf:"center"
  },
![screen shot 2017-11-04 at 1 01 19 am](https://user-images.githubusercontent.com/24516706/32388889-bbd99552-c0fb-11e7-8d12-3178058b9713.png)

**Comment by doomsower** [comment]
This is strange, I'd like to see more code. My guess is this is connected to this strange `width : "90%",` style definition, which prevents content from being measured correctly

**Comment by doomsower** [comment]
Closed as inactive.
