### ISSUE TITLE
the screen flickered when the popover is closed both in android and ios

### ISSUE THREAD

**Issue by jcliang1212** [doomsower/react-native-modal-popover#6]
when I close the popover, after the close animation is finished, the screen get a little flickered. Can you help me to resolve it ,thanks! @doomsower

**Comment by snksergio** [comment]
+1

**Comment by doomsower** [comment]
I published version 0.0.3 recently. Is this still an issue? Is this bug happening on emulator, real device or both? Could you please provide some code sample?

**Comment by WardianGames** [comment]
Happening to me too on ios. When I use the onClose event to dismiss the popover.

**Comment by snksergio** [comment]
+1, @doomsower update and take this error:
![erro](https://user-images.githubusercontent.com/8795684/33034964-a8b9eae0-ce10-11e7-8278-8f6de3f92111.png)

Before although a little slow and give a few fliks it did not accuse any kind of error, I upgraded to 0.3 ... I tested on devices and emulators, different versions of android and RN

**Comment by andfk** [comment]
+1 happening for me too :/

**Comment by thomascharbit** [comment]
Same here!

**Comment by thomascharbit** [comment]
I suspect an issue with `<ScrollView>`, here is a code sample to reproduce:

```
import React from 'react';
import { ScrollView, Button, StyleSheet, Text, View } from 'react-native';
import Popover, { PopoverTouchable } from 'react-native-modal-popover';

const App = () => (
  <ScrollView contentContainerStyle={{flex:1, justifyContent: 'center'}}>
    <PopoverTouchable onPopoverDisplayed={() => console.log('Popover displayed!')}>
      <Button title="Press me!" onPress={() => console.log('I don\'t work')}/>
      <Popover>
        <Text>Hello from inside popover!</Text>
      </Popover>
    </PopoverTouchable>
  </ScrollView>
);

export default App;
```

**Comment by thomascharbit** [comment]
Sorry for spamming your inbox, actually nothing to do with `<ScrollView>`..

But it looks a LOT like this RN Modal issue:
react-native-community/react-native-modal#92

I tried using the `hideModalContentWhileAnimating` property but didn't work 😒 
Setting `useNativeDriver` to false fixes the issue though! 😄 

I suggest giving an option to disable the native driver, which would make sense regardless of this specific bug.

**Comment by doomsower** [comment]
Thanks for doing the research. There is another solution in this thread. I will see how can I adapt both on this weekend.

**Comment by doomsower** [comment]
So I exposed `useNativeDriver` and it is false by default now. Does it solve the flickering issue?

**Comment by thomascharbit** [comment]
Works for me! 👍
