### ISSUE TITLE
how to use Popover alone? it's props visible do not work when use it alone!

### ISSUE THREAD

**Issue by ding-love-yu** [doomsower/react-native-modal-popover#7]
**//here is my code i use Popover alone but the visible prop don't work！And i can't see it on my device!!!**
import React from 'react';
import { Button, StyleSheet, Text, View } from 'react-native';
import Popover, { PopoverTouchable } from 'react-native-modal-popover';

const styles = StyleSheet.create({
  app: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#c2ffd2',
    flex:1,
  },
  content: {
    padding: 16,
    backgroundColor: 'pink',
    borderRadius: 8,
  },
  arrow: {
    borderTopColor: 'pink',
  },
  background: {
    backgroundColor: 'rgba(0, 0, 255, 0.5)'
  },
});

const App = () => (
 <View style={styles.app}>

      <Popover
        contentStyle={styles.content}
        arrowStyle={styles.arrow}
        backgroundStyle={styles.background}
        visible={true}
        fromRect={ {x:0, y:0, width:100, height:100} }
      >
        <Text>Hello from inside popover!</Text>
      </Popover>
 </View>

);

export default App;

**Comment by doomsower** [comment]
Popover is meant to be used as controlled component, `visible` should be a state.
Check out https://github.com/doomsower/react-native-modal-popover/blob/master/example/src/App2.js for example
