### ISSUE TITLE
[Android only] TypeError : expected dynamic type 'double' but had type 'string'.

### ISSUE THREAD

**Issue by ershubhamgarg** [doomsower/react-native-modal-popover#9]
@doomsower  In iOS, popover is working fine but in android simulator, it shows error :  expected dynamic type 'double' but had type 'string'. I have also tested it on device but the error is same.

**Comment by alewiahmed** [comment]
This problem is still not fixed. For anyone who is still interested, what you can do for now is comment the line that says useNativeDriver: true @ line 91 inside the popover.js file. Or if you don't want to do that, you can remove the rotate or scale fields (one of them will do) from the transform array at line 125. I think the problem is with the rotate transform for the triangle.

**Comment by doomsower** [comment]
What version of RN are you using?
I had this problem before, but then I updated example to 0.50 and I didn't need this workaround, so I removed it from the latest version. But maybe I tested it on ios only.

**Comment by wli** [comment]
@doomsower I'm using 0.50 and run into this problem on android.

**Comment by wli** [comment]
Underlying issue is here: https://github.com/facebook/react-native/issues/14161

The workarounds that @alewiahmed talked about make sense and I've tested that they work.

**Comment by ershubhamgarg** [comment]
@doomsower I am using RN version 0.44.0 and facing this problem in android only. Can you suggest something to avoid it ?

**Comment by doomsower** [comment]
@ershubhamgarg Try to use version `0.0.2` of this package, it should work on android and still use native driver. I'll partially revert 0.0.3 soon or merge @wli pr. I'm not sure if my previous workaround was any better than not using native driver at all.

**Comment by ershubhamgarg** [comment]
@doomsower Sorry but it did not help by changing the version to 0.0.2. I have still the same issue.

**Comment by ershubhamgarg** [comment]
@alewiahmed Thanks. it worked by removing scale field from transform array.

**Comment by gillesBzk** [comment]
I try the differents solution but nothing work for me :(
react-native-modal-popover": "0.0.7",
    "react": "^16.2.0",
    "react-native": "0.53.0",
